#!/usr/bin/bash
shell_cmd=$(basename $0)
shell_dir=$(dirname  $0)
shell_pwd=$(pwd)

function travel_fs() {
for element in `ls $1`; do
    if [ -d $1/${element} ]; then
      local node=$1"/"${element}
      echo "update: ${node}/Makefile"
      rm ${node}/.make/install.dir/*.ins
      cp .make/install.dir/*.ins ${node}/.make/install.dir/
      echo "done"
    fi
    # echo ${element}
done
}

echo ${shell_pwd}
travel_fs ${shell_pwd}/applications
travel_fs ${shell_pwd}/libraries
travel_fs ${shell_pwd}/modules
