#!/usr/bin/bash
shell_cmd=$(basename $0)
shell_dir=$(dirname  $0)
shell_pwd=$(pwd)

function update_makefile(){
    echo "update ${shell_pwd}/Makefile to $1/"
    cp -f ${shell_pwd}/Makefile $1/
}

function update_prepare(){ 
    for dep in `ls $1/.make/prepare.dir/*.dep`; do
        echo "update $1/.make/prepare.dir/basename:$(basename ${dep}) "
	cp -f ${shell_pwd}/.make/prepare.dir/$(basename ${dep}) $1/.make/prepare.dir/ 
    done
}

function travel_fs() {
for element in `ls $2`; do
    node=$2"/"${element}
    if [ -d ${node} ]; then
        $1 ${node}
    fi
    done
}

case ${shell_cmd} in
    update.makefile)
        travel_fs update_makefile ${shell_pwd}/modules
        travel_fs update_makefile ${shell_pwd}/libraries
	travel_fs update_makefile ${shell_pwd}/templates
        travel_fs update_makefile ${shell_pwd}/applications
	travel_fs update_makefile ${shell_pwd}/thirds
    ;;
    update.prepare)
        travel_fs update_prepare ${shell_pwd}/modules
        travel_fs update_prepare ${shell_pwd}/libraries
	travel_fs update_prepare ${shell_pwd}/templates
        travel_fs update_prepare ${shell_pwd}/applications
	travel_fs update_prepare ${shell_pwd}/thirds
    ;;
    *)
    echo "I don't know what to do."
    ;;
esac

